server:
  servlet:
    context-path: /api
  port: 8710
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easychat
    username: root
    password: 123456
  data:
    redis:
      repositories:
        enabled: true
app:
  wsPort: 5051
  projectFolder: C:/Users/easychat/
  adminEmails: 2664481691@qq.com


